using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FastPrinter.Generators;

// 1. IL MARCATORE: Questa label dice al compilatore C# (Roslyn) che questa classe è un generatore.
[Generator]
public class FastOutputGenerator : IIncrementalGenerator
{
    // 2. INIZIALIZZAZIONE: È il punto di ingresso. Viene chiamato una sola volta da Roslyn quando apri l'IDE o avvii la build.
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Creiamo una "pipeline" che osserva il codice sorgente mentre l'utente lo digita.
        var structDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                // PREDICATE (Filtro veloce): Passa solo se è una struct e ha almeno un attributo.
                // Serve per non rallentare l'IDE. Qui lavoriamo solo sulla sintassi testuale pura.
                predicate: static (s, _) => s is StructDeclarationSyntax { AttributeLists.Count: > 0 },

                // TRANSFORM (Analisi profonda): Se passa il filtro, usiamo il Modello Semantico per capire i tipi.
                transform: static (ctx, _) => GetStructToGenerate(ctx))

            // Scartiamo i null (cioè le struct che avevano attributi, ma non il NOSTRO attributo)
            .Where(static m => m is not null);

        // Registriamo l'azione finale: per ogni struct valida trovata, genera il codice.
        context.RegisterSourceOutput(structDeclarations, static (spc, structInfo) => Execute(spc, structInfo.Value));
    }

    // 3. ESTRAZIONE DATI: Qui traduciamo il codice dell'utente nei nostri DTO interni
    private static StructInfo? GetStructToGenerate(GeneratorSyntaxContext context)
    {
        // Sappiamo già che è una struct grazie al predicato
        var structDeclaration = (StructDeclarationSyntax)context.Node;

        // Il SemanticModel ci permette di fare domande del tipo: "Di che tipo è questa variabile?"
        var symbol = context.SemanticModel.GetDeclaredSymbol(structDeclaration) as INamedTypeSymbol;
        if (symbol == null) return null;

        // Controlliamo se la struct ha l'attributo [FastSerializable]
        var hasAttribute = symbol.GetAttributes()
            .Any(ad => ad.AttributeClass?.Name == "FastSerializableAttribute" ||
                       ad.AttributeClass?.Name == "FastSerializable");

        if (!hasAttribute) return null;

        // Estraiamo tutte le proprietà pubbliche della struct
        var properties = symbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Select(p => new PropertyInfo(p.Name, p.Type.ToDisplayString()))
            .ToList();

        // Estraiamo i modificatori esatti scritti dall'utente (es. "public readonly ref")
        string modifiers = structDeclaration.Modifiers.ToString();

        // Restituiamo un DTO pulito con le uniche info che ci servono per generare il testo
        return new StructInfo(
            symbol.Name,
            symbol.ContainingNamespace.ToDisplayString(),
            modifiers,
            properties);
    }

    // 4. GENERAZIONE DEL CODICE: Qui assembliamo la stringa finale che verrà aggiunta alla compilazione
    private static void Execute(SourceProductionContext context, StructInfo structInfo)
    {
        var sb = new StringBuilder();

        // Intestazione del file generato
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using lib.utils.span;"); // Il tuo namespace per i metodi AppendTo
        sb.AppendLine();
        sb.AppendLine($"namespace {structInfo.Namespace};");
        sb.AppendLine();

        // Creiamo l'altra metà della struct parziale dell'utente
        sb.AppendLine($"partial struct {structInfo.Name}");
        sb.AppendLine("{");

        // Richiamiamo i metodi helper per scrivere il corpo di ToJson e ToCsv
        GenerateToJson(sb, structInfo.Properties);
        sb.AppendLine();
        GenerateToCsv(sb, structInfo.Properties);

        sb.AppendLine("}");

        // Diciamo a Roslyn di iniettare questo nuovo file nel progetto principale
        context.AddSource($"{structInfo.Name}.FastOutput.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    // 5. SCRITTURA DI ToJson (Sfruttando le tue SpanExtensions)
    private static void GenerateToJson(StringBuilder sb, List<PropertyInfo> properties)
    {
        sb.AppendLine("    public (IMemoryOwner<char> Owner, int Length) ToJson()");
        sb.AppendLine("    {");
        sb.AppendLine("        var owner = MemoryPool<char>.Shared.Rent(1024);");
        sb.AppendLine("        var span = owner.Memory.Span;");
        sb.AppendLine("        int pos = 0;");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            \"{\".AsSpan().AppendTo(span, ref pos);");

        for (int i = 0; i < properties.Count; i++)
        {
            var p = properties[i];
            
            // Controlliamo se è un tipo testuale
            bool isString = p.Type == "string";
            bool isSpan = p.Type.Contains("ReadOnlySpan<char>") || p.Type.Contains("Span<char>");
            
            if (isString || isSpan)
            {
                sb.AppendLine($"            \"\\\"{p.Name}\\\":\\\"\".AsSpan().AppendTo(span, ref pos);");
                
                if (isString)
                {
                    // Le stringhe sono reference types, potrebbero essere null
                    sb.AppendLine($"            if ({p.Name} != null) {p.Name}.AsSpan().AppendTo(span, ref pos);");
                }
                else
                {
                    // Gli Span sono value types, si scrivono direttamente (e non serve .AsSpan())
                    sb.AppendLine($"            if (!{p.Name}.IsEmpty) {p.Name}.AppendTo(span, ref pos);");
                }
                
                sb.AppendLine("            \"\\\"\".AsSpan().AppendTo(span, ref pos);");
            }
            else
            {
                // Numeri, booleani, struct annidate (delegati ai tuoi metodi AppendTo custom)
                sb.AppendLine($"            \"\\\"{p.Name}\\\":\".AsSpan().AppendTo(span, ref pos);");
                sb.AppendLine($"            {p.Name}.AppendTo(span, ref pos);");
            }

            if (i < properties.Count - 1)
            {
                sb.AppendLine("            \",\".AsSpan().AppendTo(span, ref pos);");
            }
        }

        sb.AppendLine("            \"}\".AsSpan().AppendTo(span, ref pos);");
        sb.AppendLine("            '\\n'.AppendTo(span, ref pos);");
        sb.AppendLine("            return (owner, pos);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (ArgumentOutOfRangeException)");
        sb.AppendLine("        {");
        sb.AppendLine("            owner.Dispose();");
        sb.AppendLine("            throw new InvalidOperationException(\"Buffer troppo piccolo per il JSON\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    // 6. SCRITTURA DI ToCsv (Sfruttando le tue SpanExtensions)
    private static void GenerateToCsv(StringBuilder sb, List<PropertyInfo> properties)
    {
        sb.AppendLine("    public (IMemoryOwner<char> Owner, int Length) ToCsv()");
        sb.AppendLine("    {");
        sb.AppendLine("        var owner = MemoryPool<char>.Shared.Rent(1024);");
        sb.AppendLine("        var span = owner.Memory.Span;");
        sb.AppendLine("        int pos = 0;");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        for (int i = 0; i < properties.Count; i++)
        {
            var p = properties[i];

            if (p.Type == "string")
            {
                sb.AppendLine($"            if ({p.Name} != null) {p.Name}.AsSpan().AppendTo(span, ref pos);");
            }
            else
            {
                sb.AppendLine($"            {p.Name}.AppendTo(span, ref pos);");
            }

            if (i < properties.Count - 1)
            {
                sb.AppendLine("            ';'.AppendTo(span, ref pos);");
            }
        }

        sb.AppendLine("            '\\n'.AppendTo(span, ref pos);");
        sb.AppendLine("            return (owner, pos);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (ArgumentOutOfRangeException)");
        sb.AppendLine("        {");
        sb.AppendLine("            owner.Dispose();");
        sb.AppendLine("            throw new InvalidOperationException(\"Buffer troppo piccolo per il CSV\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    // 7. MODELLI DTO INTERNI: Strutture leggere per trasportare le informazioni 
    // dal dominio di Roslyn (Syntax/Symbols) al dominio della generazione testo.
    private readonly struct StructInfo
    {
        public string Name { get; }
        public string Namespace { get; }
        public string Modifiers { get; }
        public List<PropertyInfo> Properties { get; }

        public StructInfo(string name, string ns, string modifiers, List<PropertyInfo> properties)
        {
            Name = name;
            Namespace = ns;
            Modifiers = modifiers;
            Properties = properties;
        }
    }

    private readonly struct PropertyInfo
    {
        public string Name { get; }
        public string Type { get; }
        public PropertyInfo(string name, string type)
        {
            Name = name;
            Type = type;
        }
    }
}