using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using System.Linq;

namespace SwissCliGenerators
{
    [Generator]
    public class JsonGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var structDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) => s is StructDeclarationSyntax { AttributeLists.Count: > 0 },
                    transform: (ctx, _) => GetStructToGenerate(ctx))
                .Where(static m => m is not null);

            context.RegisterSourceOutput(structDeclarations, static (spc, structSymbol) => Execute(spc, structSymbol));
        }

        private static INamedTypeSymbol GetStructToGenerate(GeneratorSyntaxContext context)
        {
            var structDeclaration = (StructDeclarationSyntax)context.Node;
            foreach (var attributeListSyntax in structDeclaration.AttributeLists)
            {
                foreach (var attributeSyntax in attributeListSyntax.Attributes)
                {
                    if (attributeSyntax.Name.ToString().Contains("GenerateFastOutput"))
                        return context.SemanticModel.GetDeclaredSymbol(structDeclaration) as INamedTypeSymbol;
                }
            }
            return null;
        }

        private static void Execute(SourceProductionContext context, INamedTypeSymbol structSymbol)
        {
            string structName = structSymbol.Name;
            string namespaceName = structSymbol.ContainingNamespace.ToDisplayString();

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine($"namespace {namespaceName};");
            builder.AppendLine();
            builder.AppendLine($"public readonly ref partial struct {structName}");
            builder.AppendLine("{");
            builder.AppendLine("    public int ToJson(System.Span<char> output)");
            builder.AppendLine("    {");
            builder.AppendLine("        int pos = 0;");
            builder.AppendLine("        \"{\".AsSpan().AppendTo(output, ref pos);");

            var fields = structSymbol.GetMembers().OfType<IFieldSymbol>()
                .Where(f => f.DeclaredAccessibility == Accessibility.Public).ToList();

            for (int i = 0; i < fields.Count; i++)
            {
                var field = fields[i];
                if (i > 0) builder.AppendLine("        \",\".AsSpan().AppendTo(output, ref pos);");
                builder.AppendLine($"        \"\\\"{field.Name}\\\":\".AsSpan().AppendTo(output, ref pos);");

                if (field.Type.Name.Contains("ReadOnlySpan"))
                {
                    builder.AppendLine("        \"\\\"\".AsSpan().AppendTo(output, ref pos);");
                    builder.AppendLine($"        this.{field.Name}.AppendTo(output, ref pos);");
                    builder.AppendLine("        \"\\\"\".AsSpan().AppendTo(output, ref pos);");
                }
                else
                {
                    builder.AppendLine($"        if (this.{field.Name}.TryFormat(output[pos..], out int {field.Name}Chars)) pos += {field.Name}Chars;");
                }
            }

            builder.AppendLine("        \"}\\n\".AsSpan().AppendTo(output, ref pos);");
            builder.AppendLine("        return pos;");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            context.AddSource($"{structName}.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }
    }
}